package net.dark.threecore.dungeons.engine;

public record DungeonGenerationSettings(
    int maxAttempts,
    int mainPathMin,
    int mainPathMax,
    int branchMin,
    int branchMax,
    int branchLengthMin,
    int branchLengthMax,
    boolean allowVertical,
    int maxYLevelDifference,
    int maxTotalYSpan,
    int maxVerticalUp,
    int maxVerticalDown,
    boolean requireStairConnectorTypes,
    int roomPaddingBlocks,
    int connectorGapBlocks,
    double connectorOverlapToleranceBlocks,
    boolean allowTouchingAtConnectors,
    boolean requireFinalBossRoom,
    boolean bossRoomRequired,
    int minimumCompleteRooms,
    boolean preventFloatingConnectors,
    boolean sealOpenOptionalConnectors,
    boolean allowExtraEndingRooms,
    int maxExtraEndingRooms,
    String requiredOpenConnectorBehavior,
    String optionalOpenConnectorBehavior,
    boolean applyPhysics,
    boolean updateNeighbors,
    boolean preserveBlockstates,
    boolean preserveBlockEntities,
    int maxPlacementCandidates,
    double treasureChance,
    double miniBossChance
) {
    public static DungeonGenerationSettings defaults() {
        return new DungeonGenerationSettings(
            75,
            6,
            12,
            2,
            5,
            1,
            4,
            false,
            3,
            64,
            2,
            3,
            true,
            2,
            1,
            2.0D,
            true,
            true,
            true,
            8,
            true,
            true,
            true,
            0,
            "DEAD_END_OR_RETRY",
            "CAP_WITH_WALL",
            false,
            false,
            true,
            true,
            32,
            0.25D,
            0.15D
        );
    }
}
