package net.dark.threecore.dungeons.engine;

public record DungeonGenerationSettings(
    int maxAttempts,
    int mainPathMin,
    int mainPathMax,
    int branchMin,
    int branchMax,
    int branchLengthMin,
    int branchLengthMax,
    boolean allowVertical,
    int maxYLevelDifference,
    int maxTotalYSpan,
    int maxVerticalUp,
    int maxVerticalDown,
    boolean requireStairConnectorTypes,
    int roomPaddingBlocks,
    int connectorGapBlocks,
    boolean allowTouchingAtConnectors,
    boolean requireFinalBossRoom,
    boolean bossRoomRequired,
    boolean preventFloatingConnectors,
    boolean sealOpenOptionalConnectors,
    String requiredOpenConnectorBehavior,
    String optionalOpenConnectorBehavior,
    boolean applyPhysics,
    boolean updateNeighbors,
    boolean preserveBlockstates,
    boolean preserveBlockEntities,
    double treasureChance,
    double miniBossChance
) {
    public static DungeonGenerationSettings defaults() {
        return new DungeonGenerationSettings(
            75,
            6,
            12,
            2,
            5,
            1,
            4,
            true,
            3,
            64,
            2,
            3,
            true,
            2,
            1,
            true,
            true,
            true,
            true,
            true,
            "DEAD_END_OR_RETRY",
            "CAP_WITH_WALL",
            false,
            false,
            true,
            true,
            0.25D,
            0.15D
        );
    }
}
